# Generated by Django 5.1.1 on 2024-09-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.theaxebraughing.uk/wp-content/uploads/2020/04/food-placeholder-image.jpg', max_length=500),
        ),
    ]
